Fix import error `AttributeError: partially initialized module 'timesketch.lib.analyzers.interface' has no attribute 'get_yaml_config' (most likely due to a circular import)`